// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAiNyscoJ-50Xr1YNd7p2hS8mDpjfnkac',
    appId: '1:44428255895:web:5dcf493d94ff717fbd3fd2',
    messagingSenderId: '44428255895',
    projectId: 'godlife-e42a8',
    authDomain: 'godlife-e42a8.firebaseapp.com',
    storageBucket: 'godlife-e42a8.appspot.com',
    measurementId: 'G-YC4P0K54YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1oZ-43lvNSYInaEzf9XR4cTRmhHJVY3w',
    appId: '1:44428255895:android:b3b7159b601181bcbd3fd2',
    messagingSenderId: '44428255895',
    projectId: 'godlife-e42a8',
    storageBucket: 'godlife-e42a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATfIDk7sLXfV1zu87uiRz-Clh4uCeCQPs',
    appId: '1:44428255895:ios:d64809df64e99441bd3fd2',
    messagingSenderId: '44428255895',
    projectId: 'godlife-e42a8',
    storageBucket: 'godlife-e42a8.appspot.com',
    iosClientId: '44428255895-hq1qg8c9srp6ee1vt79vkep4e16e3pv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.godLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATfIDk7sLXfV1zu87uiRz-Clh4uCeCQPs',
    appId: '1:44428255895:ios:d64809df64e99441bd3fd2',
    messagingSenderId: '44428255895',
    projectId: 'godlife-e42a8',
    storageBucket: 'godlife-e42a8.appspot.com',
    iosClientId: '44428255895-hq1qg8c9srp6ee1vt79vkep4e16e3pv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.godLife',
  );
}
